// AUTO-GENERATED by scripts/gen-changelog.mjs — DO NOT EDIT.
// 数据源：根目录 CHANGELOG.md（Keep a Changelog），唯一手写源；predev/prebuild 自动重新生成。
import type { ChangelogEntry } from "./about";

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.2.23",
    date: "2026-07-12",
    highlights: [
      "MCP 后端分发层重构：手写 `match` 分发改为「工具注册表 + `ToolSchema` 派生宏」，17 个工具的 `inputSchema` 自动从 handler 的 Args struct 派生，新增工具零样板、协议契约与代码同源",
      "新增 over-the-wire 集成测试：真实起 MCP server + 真实 reqwest 客户端端到端验证协议握手、17 工具分发与落盘副作用、鉴权 / 限流 / gzip / 错误码，测试套件 72 → 82 全绿、`cargo clippy --no-default-features` 零警告",
      "连接页方案 A 完整落地：Token 内嵌复制命令、`s-sec-label` 安全分区、渐变徽章步骤、灰底命令框、步骤行 hover",
    ],
    items: [
      { category: "feat", text: "工具注册表 `src/mcp/tools/registry.rs`：集中声明 17 个工具的名称 / 读写属性 / handler 分发，替代散落各处的 `match` 分支" },
      { category: "feat", text: "`ToolSchema` 派生宏（新增 `cc-bridge-macros` proc-macro crate，仅编译期依赖、不进 exe，守二进制体积红线）：从工具 Args struct 自动生成 `inputSchema`" },
      { category: "feat", text: "over-the-wire 集成测试模块（`http.rs`，10 个用例）：initialize 回显 / tools/list=17 / 未知方法 -32601 / 全工具分发+副作用 / 后台 run→output→stop 三元组 / auth 401·200 / 限流 429 / gzip 响应头" },
      { category: "feat", text: "关于页 `ChangelogView` 组件 + `scripts/gen-changelog.mjs` + `src/lib/changelog.generated.ts`，更新历史从 `CHANGELOG.md` 自动同步" },
      { category: "feat", text: "`TokenManager.tsx` 令牌管理界面" },
      { category: "improve", text: "后端分发由 `match` 分支改为 registry 查表分发，全部 17 个工具接入注册表" },
      { category: "improve", text: "连接页方案 A 完整落地：Token 内嵌复制命令、`s-sec-label` 分区、渐变徽章步骤、灰底命令框、步骤行 hover（PastePanda 风格优化）" },
      { category: "improve", text: "后端性能与质量优化：`config.rs` / `audit.rs` / `db.rs` / `main.rs` 模块重构" },
      { category: "fix", text: "`notebook_edit` 驼峰 `newSource` 字段被静默忽略：该字段此前只有 `#[serde(default)]` 缺 `#[serde(rename = \"newSource\")]`，客户端按文档传 camelCase 时单元格被清空为 `\"\"`；补 rename 后修复（此缺陷因既有单测直接构造 Rust struct、从未走 JSON 反序列化而长期未发现，恰由本次 over-the-wire 测试捕获）" },
      { category: "improve", text: "`reqwest` / `axum` 作为 dev-dependency 支撑集成测试，`default-tls` 在 Windows 走系统 schannel，无需 openssl 编译" },
    ],
  },
  {
    version: "2.2.22",
    date: "2026-07-11",
    highlights: [
      "关于页与连接页全面改用 PastePanda 风格，信息更清晰、操作更顺手",
      "扩展名可按类别勾选，白名单配置更快",
    ],
    items: [
      { category: "feat", text: "关于卡片 PastePanda 风格重写：默认收起成一行，点开双列展示（技术栈 + 项目信息），更新历史按「新增 / 改进 / 修复 / 安全」分类标签呈现，详情弹框介绍完整能力。" },
      { category: "feat", text: "Header 版本号支持一键检查更新：空闲时点击即可检查，覆盖检查中 / 有新版 / 下载中 / 待重启 / 已最新 / 出错等状态。" },
      { category: "feat", text: "托盘图标升级：改用应用真图标，并在右下角叠加运行状态小圆点。" },
      { category: "feat", text: "扩展名芯片输入：常用扩展名按「前端 / 后端 / 配置 / 文档」分类，点开勾选、分色显示；也支持自定义输入（回车、逗号、粘贴拆分）。" },
      { category: "improve", text: "文件管控改用行式渐变徽章，备份与限流配置更紧凑直观。" },
      { category: "improve", text: "网络卡片端口与保存按钮同行，去掉容易误解的「当前地址」行。" },
      { category: "improve", text: "安全概览标题与展开箭头合并为一行，整行可点。" },
      { category: "improve", text: "全应用统一为「CC Bridge」名称（此前部分界面显示小写 cc-bridge）。" },
      { category: "improve", text: "移除冗余输入组件、改用语内联输入；补充图标；Rust 与 TypeScript 均零警告。" },
    ],
  },
  {
    version: "2.2.17",
    date: "2026-07-10",
    highlights: [
      "新增 Notebook 编辑能力，AI 可直接改 .ipynb",
    ],
    items: [
      { category: "feat", text: "新增 `notebook_edit` 工具：可按单元格对 `.ipynb` 笔记本做替换 / 插入 / 删除，AI 编辑 Notebook 更顺手（只读模式会拒绝该写类工具）。" },
      { category: "improve", text: "搜索文件增强：支持大小写不敏感、上下文行、行号、输出模式（仅路径 / 计数 / 内容）等富选项。" },
      { category: "improve", text: "新增 11 个单元测试，测试套件 41 → 52 全绿。" },
    ],
  },
  {
    version: "2.2.16",
    date: "2026-07-10",
    items: [
      { category: "improve", text: "后台命令整树终止改用社区成熟方案（process-wrap），替代手写的 Windows 进程管理，跨平台更可靠。" },
      { category: "improve", text: "修复「先启动子进程再挂入进程组」之间的竞态窗口，孙进程不再漏杀。" },
      { category: "improve", text: "移除自写的进程管理代码，依赖更精简；`cargo test` 41 全绿、零警告。" },
    ],
  },
  {
    version: "2.2.15",
    date: "2026-07-10",
    items: [
      { category: "improve", text: "当前为启发式拦截（最低成本兜底），误伤与漏拦并存，后续会升级为更严谨的沙箱。" },
    ],
  },
  {
    version: "2.2.14",
    date: "2026-07-10",
    items: [
      { category: "fix", text: "根治真实程序（如 git.exe / cargo.exe）执行后读不到输出的问题：改用标准管道直接启动，命令输出现在能正确捕获、标准错误也不再恒为空。" },
      { category: "improve", text: "移除不可用的终端模拟方案，依赖更干净。" },
    ],
  },
  {
    version: "2.2.13",
    date: "2026-07-10",
    items: [
      { category: "improve", text: "后台命令整树终止改用 Windows 进程组，子进程 / 孙进程不再漏杀，应用异常退出也不会留下孤儿进程。" },
      { category: "improve", text: "搜索文件改用成熟目录遍历库，自动跳过 node_modules / target 等，跨目录 glob 匹配终于好用。" },
      { category: "improve", text: "写文件结果新增改动对比（diff），AI 改动前你能先核对。" },
      { category: "fix", text: "清理一批过时代码检查告警；删除一处从未被引用的死代码（限流模块）。" },
    ],
  },
  {
    version: "2.2.8",
    date: "2026-07-10",
    items: [
      { category: "feat", text: "首次使用引导 `OnboardingGuide`：三步引导用户添加白名单目录 → 复制连接命令 → 启动服务，本地 `localStorage` 记忆已引导状态，仅首次弹出。" },
      { category: "feat", text: "命令面板 `CommandPalette`（Ctrl+K / ⌘K）：键盘快速切换 4 个 Tab，支持搜索、↑↓ 导航、Enter 确认、Esc 关闭；全局快捷键 Ctrl+1~4 直跳 Tab。" },
      { category: "feat", text: "连接页 Hero 卡升级：新增启停大按钮（loading 态 + 内联错误提示）、指标变化弹跳动画、运行时长平滑跳秒（本地每秒自增 + 5s 轮询校准）。" },
      { category: "feat", text: "安全页「运行中的后台命令」卡片：列出 `run_command(background=true)` 启动的进程（PID/命令/已运行时长），一键终止，与远程 `get_command_output` 共享注册表。" },
      { category: "feat", text: "安全页白名单目录搜索框 + 扩展名预设快捷填充（前端常用/后端常用/配置文件/文档类）。" },
      { category: "feat", text: "日志页升级：搜索 + 工具/状态筛选、JSON/CSV(Excel) 导出、行展开查看参数详情（高亮代码块 + 复制）、清空日志二次确认。" },
      { category: "feat", text: "托盘增强：图标随服务运行状态切换（运行时绿点 / 停止灰点，代码生成无需额外资源）；左键点击托盘 toggle 主窗口显隐；右键菜单新增「复制连接命令」（经前端通道写剪贴板 + toast）；tooltip 实时显示「运行中 / 已停止 / 地址变化」；启停时即时刷新托盘（通过 `mcp-status-changed` 事件）。" },
      { category: "feat", text: "主题切换过渡动画：深/浅色切换时颜色类属性 0.45s 平滑过渡，切换瞬间临时启用 `theme-transition` 避免常驻 transition 拖累性能与首屏闪烁。" },
      { category: "improve", text: "`tabs.tsx` 升级为 segmented pill 滑动指示器（绝对定位高亮块 + transform 过渡，窗口 resize 重算），替代旧静态高亮。" },
      { category: "improve", text: "`SettingsToggles` 新增「命令执行」开关，开启等同授予 RCE，需勾选风险确认的二次确认弹窗；新增「恢复默认设置」按钮。" },
      { category: "improve", text: "`StatusResponse` 新增 `lastSelectedIp` / `ipChanged` 字段，IP 选中态提升到 App 层，重启后用上次确认 IP 回填，避免切 Tab 丢失。" },
      { category: "fix", text: "连接页 Hero 卡 4 列指示签删掉「在线客户端」（后端从未实现该字段，前端一直显示 `--`），改为 3 列（总请求 / 错误 / 运行时间）。" },
      { category: "fix", text: "Hero 主题适配：拆分 `--hero-gradient` / `--hero-shadow` / `--hero-glow-1/2` / `--hero-metric-bg/border` / `--hero-addr-bg/border` 变量，两主题各配一份，深色下渐变降饱和 + 加白边避免融背景；装饰光晕深色下透明度砍半避免刺眼；指标卡补玻璃质感（`backdrop-filter: blur(4px)` + 半透明背板）。" },
      { category: "fix", text: "LogTab 清理：删除未使用的 `PAGE_SIZE` / `totalPages` / `paged` memo / `useEffect` 同步分页 / `useState(0)` 状态（前端实际未做分页 UI）；`tsc --noEmit` 现在 0 错误。" },
      { category: "fix", text: "类型修正：`ConnectHero.tsx` 的 `HeroMetric` 指标签 `icon` 字段从字面量字符串联合扩为完整 `IconName`（避免新增 `Icon` 类型时回归报错）；`button.tsx` 删除未使用的 `ReactNode` 导入。" },
      { category: "fix", text: "`package.json` 版本号同步到 2.2.8（之前漏改）。" },
    ],
  },
  {
    version: "2.2.7",
    date: "2026-07-10",
    items: [
      { category: "improve", text: "v2.2.2 → v2.2.6 release 期间累积改动合并提交：" },
      { category: "improve", text: "后端：注册 `start_update` 等 Tauri command、补 `tauri-plugin-updater` / `tauri-plugin-notification` / `tauri-plugin-process` 依赖，`main.rs` 调整启动流程。" },
      { category: "improve", text: "前端设计系统升级：靛蓝主题色、玻璃指标卡、segmented pill Tab、`TitleBarControls` 自绘标题栏、`Toast` 统一反馈组件、`index.css` +220 行新样式变量。" },
      { category: "improve", text: "`UpdateContext` 抽出更新状态层；`Header` 拆 `UpdateBadge`；多个 tab 卡片样式更新。" },
      { category: "improve", text: "图标套件重新生成（18 个 png/ico 体积变化）。" },
    ],
  },
  {
    version: "2.2.6",
    date: "2026-07-09",
    items: [
      { category: "fix", text: "同步 `Cargo.lock` 中 v2.2.5 版本号（之前 2.2.5 release 时 sync-version 触发了 lock 重生但未提交）。" },
    ],
  },
];
