// AUTO-GENERATED by scripts/gen-changelog.mjs — DO NOT EDIT.
// 数据源：根目录 CHANGELOG.md（Keep a Changelog），唯一手写源；predev/prebuild 自动重新生成。
import type { ChangelogEntry } from "./about";

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.3.16",
    date: "2026-07-24",
    items: [
      { category: "feat", text: "新增桌面通知能力与命令安全策略" },
      { category: "fix", text: "修复发版脚本防漏纳门禁误判（已暂存文件被判为漏纳而中止发版）" },
    ],
  },
  {
    version: "2.3.15",
    date: "2026-07-23",
    items: [
      { category: "improve", text: "工具写权限清单改为运行时从注册表推导，移除硬编码" },
      { category: "fix", text: "修复关于卡片进设置页无条件展开回归" },
      { category: "fix", text: "修复状态响应缺 project_path 字段导致前端 project 模式回填空值" },
      { category: "fix", text: "修复停止命令未真正终止后台子进程" },
      { category: "fix", text: "修复备份清理按文件名误删其他备份（改为按原始路径精确匹配）" },
    ],
  },
  {
    version: "2.3.14",
    date: "2026-07-23",
    items: [
      { category: "feat", text: "命令会话持久化新增环境变量跨调用重放：run_command 支持 env 参数，可为会话持久化环境变量（如 venv 的 PATH/VIRTUAL_ENV），默认关闭。" },
      { category: "fix", text: "网络变化时连接页 IP 未刷新：后端改为独立 5s 轮询刷新地址，前端监听 online/focus 事件并在连接页提供手动刷新按钮。" },
      { category: "fix", text: "设置小红点每次进入软件都显示：首屏 status 未加载时不再误判为全部未读；进入设置页即标记已读。" },
      { category: "fix", text: "连接页 4 个卡片默认全展开：改为默认折叠、单选聚焦，老用户不再被引导霸屏。" },
    ],
  },
  {
    version: "2.3.13",
    date: "2026-07-22",
    items: [
      { category: "fix", text: "执行命令弹出黑框：发布版执行 cmd/bash 命令不再弹出黑色控制台窗口，命令在后台安静执行。" },
      { category: "fix", text: "关于卡片无故展开：没有新版本更新时，关于页「更新历史」卡片不再自动展开红点提示。" },
      { category: "improve", text: "后台命令整行可点：运行中或已结束的后台命令列表，点击整行即可展开查看输出，不必再精准点「查看输出」按钮。" },
      { category: "improve", text: "write_files 覆盖已有文件时自动保留原编码：原文件是 GBK 等中文编码时，会探测并沿用原编码，不再默认按 UTF-8 覆写导致中文乱码；新建文件或关闭自动识别时仍按 UTF-8。" },
    ],
  },
  {
    version: "2.3.12",
    date: "2026-07-22",
    items: [
      { category: "fix", text: "CI 构建失败：修复 `tauri build` 在 GitHub Actions 中找不到 tauri 命令的问题（预构建脚本改写 package.json 导致 PATH 丢失，改为分离执行 + npx 调用）。" },
    ],
  },
  {
    version: "2.3.11",
    date: "2026-07-21",
    items: [
      { category: "fix", text: "设置页每次打开都亮小红点：未读基准改为「上次浏览版本」或「当前运行版本」兜底，仅真有更新时才亮。" },
      { category: "fix", text: "托盘图标闪烁。" },
      { category: "fix", text: "IP 变化提示：连接页新增 IP 变化 banner 与倒计时提示。" },
      { category: "feat", text: "红点可点击引导：点设置 tab 红点或关于卡片红点，自动展开「更新历史」并滚动定位，看完数秒后自动标记为已读。" },
      { category: "feat", text: "连接页「接入模式」折叠区：原常驻的作用域选择收为手风琴第 1 折叠区，折叠头实时显示当前选中的模式；首次接入（无引导标记）默认四块全展开引导。" },
      { category: "improve", text: "更新检查弹框分流：自动 / 启动检查更新只在版本号上提示，仅手动点「检查更新」才弹「已是最新版本」框。" },
      { category: "improve", text: "首次接入引导更顺：首次全展开时页面不再自动滚动跳动（连接页与令牌管理的滚动逻辑跳过首屏）。" },
    ],
  },
  {
    version: "2.3.10",
    date: "2026-07-21",
    items: [
      { category: "fix", text: "托盘「复制 IP 命令」跟随连接页作用域：此前托盘端固定复制用户级（~/.claude.json）命令，与连接页选「项目级」时显示的 .mcp.json 命令对不上；现托盘端读取连接页实际选择的作用域与项目路径，生成与连接页逐字一致的命令。" },
      { category: "fix", text: "连接页切换「项目级 / 全局模式」后托盘命令不联动：作用域与项目路径没有真正写入持久化配置，托盘端一直读到默认作用域；现已在切换或首次打开连接页时即时落盘，托盘复制命令与连接页保持同步。" },
    ],
  },
  {
    version: "2.3.9",
    date: "2026-07-21",
    items: [
      { category: "feat", text: "设置页「安装与快捷方式」卡片与命令面板（Ctrl+K）新增「重新查看使用引导」入口，关闭引导后可随时重新打开（H3）。" },
      { category: "feat", text: "`search_files` 结果截断回显：命中数超过上限时，在结果后附提示，告知远程 Claude Code 结果不完整、可缩小范围或翻页。" },
      { category: "fix", text: "新手引导交互缺陷（H3）：点击遮罩不再永久关闭引导（改为轻微抖动，提示改用下方按钮），消除「误触遮罩即永久跳过」；每步新增完成态——完成时标题右侧显「已完成」，未完成时底部给轻量提示（软引导，不强制拦截「下一步」）。" },
      { category: "fix", text: "全量代码审计后的一批后端健壮性修复：内容搜索非法/超长正则、结构异常的 .ipynb 不再触发进程 panic；备份保留数设为 0 不再误删全部历史备份；批量操作子项补记来源 IP；后台命令的临时工作目录捕获文件读后即删、不再累积；托盘图标非正方形时缩放越界；审计缓存判定与读取的竞态；目录递归补深度与总条目上限；大文件分析只读前缀避免 OOM；整份配置写入改为事务式、中途失败自动回滚不残留未结束事务；SSE 推送滞后丢帧改为记录日志。" },
      { category: "fix", text: "前端健壮性修复：日志详情行展开在轮询刷新后错位（改用稳定 key）；CSV 导出加公式注入防护；性能面板统计改为覆盖最近 500 条且耗时拆解不再重复计数；分页在总数缩减后不再停在空页；设置保存/目录浏览失败给出可见反馈；更新事件监听在快速重挂载下的注册竞态；主动停服不再被误判为「网络恢复」并自动重启；命令/脚本生成中的项目路径统一加引号；版本比较容忍带后缀的版本号。" },
      { category: "fix", text: "`read_files` 二进制守卫增强：PNG / EXE 等二进制此前会经 `read_text` 的 GBK 回退误判为文本、返回满屏乱码污染远端上下文；现通过内容 NUL / 非打印字符检测，在读取前拦截并返回友好提示。" },
      { category: "improve", text: "MCP `initialize` 握手 instructions 文案补充：建议连接后第一步调用 `list_allowed_roots`，自动内嵌各根目录顶层 CLAUDE.md（projectInstructions），无需再手动 read_files 就能获知项目规则。" },
      { category: "improve", text: "`edit_files` 在 `old_string` 首尾含空格 / 制表符 / 换行 / 回车时返回 `warning`，主动提醒模型确认是否多带了空白，减少「0 次匹配」导致的重试往返。" },
      { category: "sec", text: "`edit_files` 之前无视 `encoding_detect_enabled`（默认关）无条件自动探测编码，与 `read_files`（关时强制 UTF-8）不一致，可能对同一文件解码出不同内容；现两者判断逻辑一致。" },
      { category: "sec", text: "`encoding::read_text` 自动探测四种编码全部失败时会静默用 U+FFFD 替换并可能在写回时永久损坏原文；现改为拒绝并报错，提示显式指定编码。" },
      { category: "sec", text: "未配置访问令牌（空 token）不再等同于放行：`verify_token` 对空期望值失败关闭（fail-closed），杜绝空配置被无鉴权访问。" },
      { category: "sec", text: "一键回滚（restore_file）补齐只读模式与扩展名白名单校验，堵住经回滚通道绕过写入闸门的路径。" },
      { category: "sec", text: "白名单目录删除改为按路径匹配，修复重复目录/轮询刷新下删错目标；新手引导添加白名单去重。" },
      { category: "sec", text: "默认 cmd 壳层补充 Windows 破坏性命令拦截（rd/rmdir/del /s、diskpart、cipher /w 等）；`is_binary_content` 修正 UTF-32BE BOM 误判为二进制。" },
      { category: "sec", text: "只读模式开启时安全风险总览不再因 shell 开关配置值而误报「高风险 RCE」（只读会强制禁用命令执行）。" },
    ],
  },
  {
    version: "2.3.8",
    date: "2026-07-18",
    items: [
      { category: "feat", text: "传输模式开关（HTTP / SSE）：设置页新增「传输协议」切换，默认 HTTP；切到 SSE 时弹出现成迁移命令（移除旧 HTTP 配置 + 用 SSE 端点重新添加），复制即可让远端改用流式连接" },
      { category: "feat", text: "SSE 流式服务端：新增 SSE 端点与消息通道，支持流式返回命令执行结果，远端可实时看到输出" },
      { category: "feat", text: "连接页命令随传输模式联动：选 SSE 时连接命令与托盘复制命令自动指向 SSE 端点" },
      { category: "feat", text: "bash 探测兜底：本地装了 Git for Windows 但没单独装 bash 时，自动按 Git 安装目录推导 bash 路径（支持三种常见布局），设置页「命令执行壳层」不再误报「未检测到」" },
      { category: "fix", text: "启动 / 探测 bash 时偶发闪一下黑窗口：`where bash` / `where git` 探测加上不弹窗标志" },
      { category: "fix", text: "日志页搜索框聚焦时出现一圈难看的内边框高亮：调整聚焦样式，只保留外层高亮" },
      { category: "fix", text: "版本历史弹框「看改了什么」内容超宽需横拉滚动条：长行自动换行，无需左右拖动" },
      { category: "improve", text: "连接页整体重构为手风琴模式：首次使用自动展开「权限自动授权 / 接入步骤」，之后默认收起、可手动展开；一次只展开一个区块，展开时平滑动画并自动滚动到视野内" },
      { category: "improve", text: "连接页「传输安全提醒」常驻提示移除，避免造成不必要的使用顾虑" },
      { category: "improve", text: "版本历史弹框「打开」按钮风格统一（去掉箭头、文字居中）；新增一键全屏放大，长内容查看更方便" },
      { category: "improve", text: "连接页 HTTP / SSE 状态改为配色徽章（靛蓝 / 蓝）直观区分" },
      { category: "improve", text: "连接页、令牌管理、命令面板等折叠 / 列表增删增加平滑过渡动画，交互更顺滑" },
      { category: "improve", text: "ConnectTab 组件瘦身（约 333 → 190 行），结构更清晰、便于维护" },
    ],
  },
  {
    version: "2.3.7",
    date: "2026-07-18",
    items: [
      { category: "improve", text: "审计日志读取更快：空闲轮询时不再反复解析整个日志文件" },
      { category: "improve", text: "白名单校验更快：允许访问的目录路径只标准化一次，工具反复调用不再重复计算" },
      { category: "improve", text: "网络 IP 列表获取更快：不再每 5 秒扫描一遍网卡，联网变化时才刷新" },
      { category: "improve", text: "日志页面更跟手：隔离了后台状态轮询引发的整页重算，翻页与筛选更顺滑" },
      { category: "fix", text: "修复导入配置后新目录未立即生效的问题" },
      { category: "feat", text: "更新弹框升级路径更直观：清晰展示「当前版本 → 新版本」" },
      { category: "improve", text: "更新弹框内容展示更聚焦，只呈现对你有用的要点" },
    ],
  },
];
