// AUTO-GENERATED by scripts/gen-changelog.mjs — DO NOT EDIT.
// 数据源：根目录 CHANGELOG.md（Keep a Changelog），唯一手写源；predev/prebuild 自动重新生成。
import type { ChangelogEntry } from "./about";

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.3.20",
    date: "2026-08-03",
    items: [
      { category: "fix", text: "后台有个线程会长期占满一个 CPU 核心，现已修复；同一个问题还让「IP 变化提示」一直没能生效，也一并修好" },
      { category: "fix", text: "命令超时后不再丢弃已经跑出来的输出，默认超时也从 30 秒放宽到 2 分钟" },
      { category: "fix", text: "修好三个远程工具参数「传了不生效」的问题：命令超时、输出上限、批量操作出错是否中断" },
      { category: "improve", text: "窗口收进托盘或最小化后，各类后台轮询与常驻动画全部暂停，不再空耗 CPU" },
      { category: "improve", text: "数据库日志文件从约 4MB 收回到 0，启动更快" },
      { category: "improve", text: "刷新状态时的界面重绘范围大幅收窄，日志翻页也更省内存" },
      { category: "improve", text: "一个线程常驻跑满一个 CPU 核：`ip_watch.rs` 用 winsock2 `SIO_ADDRESS_LIST_CHANGE` ioctl 监听地址变化，并把 `-1 + WSAEFAULT(10014)` 当成「地址已变化 / 有数据准备好」。实机探针测得该调用在 `cbOutBuffer=0` 时 0.000ms 立即返回 WSAEFAULT —— WSAEFAULT 意为「输出缓冲区参数无效」，即 ioctl 直接失败、通知根本没挂上。于是那个 `loop` 每秒空转数百万次（实测单线程 101.3% 单核，进程合计 125%）。改用 iphlpapi `NotifyAddrChange(NULL, NULL)`（同步阻塞，已用探针验证真的会阻塞）。" },
      { category: "improve", text: "IP 变化检测实际上一直是死的（上一条的连带后果）：假事件洪流让防抖的无限吸收循环 `while timeout(600ms, rx.recv()).is_ok()` 恒真、永不退出，其后的 `refresh_lan_ips` 与托盘提示从来执行不到（只有 5s 轮询那条兜底路径在工作）。现吸收循环加上限（最多 32 条）。" },
      { category: "improve", text: "命令超时就什么都拿不到：`run_command` 超时分支里 `stdout`/`stderr` 是硬编码的空串，已跑出来的输出全部丢弃。按 1281 条真实审计记录，141 次（11%）撞到了 30s 默认超时（而 p50 只有 1125ms，被截断的都是 cargo build 这类长命令）——编译跑了半分钟、报错都刷出来了，调用方却只拿到一个空结果。现默认超时提到 120s，且超时时会等读取线程把缓冲区吐完（最多 100 × 2ms），把真实输出连同 truncated 标记一起带回，并附提示引导长任务用 `background: true`。新增两条回归测试锁住行为。（注：这不等于「超时自动转后台」，那仍待做。）" },
      { category: "improve", text: "三个 MCP 工具参数一直是失效的（传了等于没传）：`run_command` 的 `timeoutMs` / `maxOutputBytes` 与 `batch` 的 `stopOnError`，在工具 schema 里被暴露成 snake_case（`timeout_ms` 等），而服务端反序列化只认 camelCase——于是调用方按 schema 传参会被静默忽略、永远回落默认值（实际踩到：传 `timeout_ms: 180000` 仍按默认超时结束）；另 `search_files` 的 `maxResults` 被误标成必填。根因在 `ToolSchema` 衍生宏：`parse_nested_meta` 的回调未把非目标项的 `= value` 消费掉，解析在第一个不关心的带值项处就报错并被吞，属性里后续项全部读不到（具体丢 `rename` 还是丢 `default` 取决于两者的书写顺序，所以症状看上去毫无规律）。现改为对所有带值项统一先吃下值再取用，并补两条断言 schema 形状的回归测试（这类 bug 不报错、不失败构建）。注：这会使上述参数名在 schema 里改为 camelCase，但它们原本传了也无效，不存在有效依赖。" },
      { category: "improve", text: "新增两道护栏防止同类问题再现：通知 API 返回非预期值时强制退避 2s（绝不空转）；事件频率硬限流 ≤ 5 次/秒。即使将来 API 行为再变，最坏也只退化成每 200ms 一次，不会再烧掉一个核。" },
      { category: "improve", text: "前端常驻脉冲点从动画 `box-shadow`（每帧重绘，且紧邻 `backdrop-filter` 元素会连带大面积背景重新模糊）改为伪元素的 `transform + opacity` 涟漪（纯合成）；`indet-slide` 从动画 `left`（每帧布局）改为 `transform: translateX`；删掉死代码 `uptime-flash` / `.hero-uptime--live`。新增「窗口不可见时暂停全部动画」机制（`data-app-hidden` + `hooks/useAppHiddenFlag.ts`，Rust 侧在托盘 toggle / 托盘菜单显示 / 关窗收托盘 / OS 最小化四处发 `app:visibility`）。暂停范围只限于 7 个常驻 `infinite` 动画，不碰 transition 与一次性入场动画——最初写成 `*` 加 `transition: none !important`，实际跑起来整页白屏（会把正在入场的元素永久冻在 `opacity: 0`），已改窄并在 CSS 里留下警告。另：早前“暂停未生效”的结论已被推翻（那次测量未受控，见清单 M10），信号计算现有单测兜底；但真实 CPU 收益仍待受控复测。" },
      { category: "improve", text: "`ip_watch::spawn` 不再返回 `UdpSocket`（改用 `NotifyAddrChange` 后不再需要用 socket 关闭作为停止信号）；线程以 `tx.send` 失败作为退出条件。" },
      { category: "improve", text: "新增 `desktop/src-tauri/ip_watch_probe.rs`（独立诊断工具，不在 `src/` 下、不参与 Cargo 构建）：一次性验证两个通知 API 的阻塞行为，以后怀疑同类问题直接 `rustc ip_watch_probe.rs -O -o ip_watch_probe.exe` 跑一次即可。" },
      { category: "improve", text: "日志面板取一页不再克隆全量：`audit.rs` 的 `read_page` 原先把缓存里整份 4898 条 / 5.2MB 的解析结果 `clone()` 一份（另有一次 `parsed.clone()`），而调用方只要几十条；前端 10s 轮询一次，即每 10s 白白克隆再丢弃两份 5MB。现改为 `page_slice()` 只克隆本页。（`AUDIT_CACHE` 本身常驻内存的问题仍在，待做。）" },
      { category: "improve", text: "WAL 文件从 3.94MB 降到 0：实测 `cc-bridge.db` 仅 448KB 而 `cc-bridge.db-wal` 高达 4.13MB——SQLite 默认 `wal_autocheckpoint` 是 1000 页（≈4MB），而本应用写入量小、进程常驻，几乎碰不到该阀值。修法分两层：① `wal_autocheckpoint` 设为 256 页（≈1MB 就回写）防它继续长，不设更小是因为太小会把随机写变成频繁 fsync；② 光有①不够——autocheckpoint 只把内容回写主库并重置写指针复用同一个文件，从不缩小文件本身（实测只加①重启后 WAL 依旧 4.13MB），所以又在启动时补一次 `wal_checkpoint(TRUNCATE)` 把残留 WAL 截到 0。实测：WAL 4132392 → 0 bytes、主库 +16KB（内容回写），净省 3.94MB，并减少每次启动的 WAL replay。" },
      { category: "improve", text: "5s 状态轮询不再连带重渲染整个 Tab：有 8 个组件直接吃 `status`，而 `uptimeSeconds` / `stats` 每 5s 必变 → 顶层引用必然是新的，包 `memo` 也挡不住（react-query 的 structuralSharing 只保得住未变字段的引用，救不了顶层对象）。现按变化频率拆订阅：新增 `StaticStatus` / `LiveStatus` 两个类型，主查询用 `select` 剔掉高频字段，`ConnectHero` 用同一 `queryKey` 自行订阅那两个字段（共享缓存，不多发请求），秒级变化只重渲染它自己。注：重渲染范围尚未用 React DevTools 实测确认。" },
      { category: "improve", text: "窗口收进托盘后不再空转轮询：以前窗口不可见时，8 处轮询依旧全速跑——状态（5s）、审计日志（10s）、防火墙诊断（30s）、后台命令列表与输出（各 3s）、运行时长跳秒（1s），其中最重的是状态轮询里带的可达性探针（真开一次 TCP 连接，200ms 超时）。现全部随窗口可见性断流，恢复可见那一刻立即补一次而不干等周期。新增 `lib/appVisibility.ts`（模块级 store + `useSyncExternalStore`）把可见性从“只写 DOM 属性”升级为 React 可订阅状态，并配 6 条单测。一次性倒计时（IP 变化提示）与小时级更新检查有意不断。" },
      { category: "improve", text: "状态查询不再用读锁罩住磁盘与网络 I/O：`get_status` 的 `config` 读锁原本从函数开头一路罩到末尾，横跨了首次防火墙查询（netsh，可达数百 ms）、可达性探针（最长 200ms）与备份目录枚举，于是前端每 5s 轮询一次就造出一个最长 200ms+ 的窗口，期间在设置页改任何配置都得排队等锁。现拆为「短锁取字段 → 锁外做慢操作 → 再取锁读剩下」，锁持有时间降到微秒级。（附：同时用探针实测排除了两个怀疑——备份目录统计在 1230 个文件下只 2.3ms，bash 探测已有缓存，两者都不是瓶颈。）" },
    ],
  },
  {
    version: "2.3.19",
    date: "2026-08-02",
    items: [
      { category: "feat", text: "安装时可勾选一键放行 Windows 防火墙，省去首次启动被拦截的麻烦" },
      { category: "sec", text: "命令拦截从子串黑名单升级为语法感知分析，更精准地拦截危险命令" },
      { category: "improve", text: "日志分页改为窗口内滚动，操作时不再被外层滚动带走" },
      { category: "improve", text: "连接页改用纯 CSS 动态表达，体积更小、运行更顺" },
    ],
  },
  {
    version: "2.3.18",
    date: "2026-07-24",
    items: [
      { category: "fix", text: "用 notifications cargo feature 替代 cfg(not(test))，修复集成测试 0xc0000139" },
    ],
  },
  {
    version: "2.3.17",
    date: "2026-07-24",
    items: [
      { category: "fix", text: "修复 test 二进制加载 GUI DLL 导致 0xc0000139 崩溃" },
      { category: "fix", text: "同步 Cargo.lock 版本号至 2.3.16" },
    ],
  },
  {
    version: "2.3.16",
    date: "2026-07-24",
    items: [
      { category: "feat", text: "新增桌面通知能力与命令安全策略" },
      { category: "fix", text: "修复发版脚本防漏纳门禁误判（已暂存文件被判为漏纳而中止发版）" },
    ],
  },
  {
    version: "2.3.15",
    date: "2026-07-23",
    items: [
      { category: "improve", text: "工具写权限清单改为运行时从注册表推导，移除硬编码" },
      { category: "fix", text: "修复关于卡片进设置页无条件展开回归" },
      { category: "fix", text: "修复状态响应缺 project_path 字段导致前端 project 模式回填空值" },
      { category: "fix", text: "修复停止命令未真正终止后台子进程" },
      { category: "fix", text: "修复备份清理按文件名误删其他备份（改为按原始路径精确匹配）" },
    ],
  },
  {
    version: "2.3.14",
    date: "2026-07-23",
    items: [
      { category: "feat", text: "命令会话持久化新增环境变量跨调用重放：run_command 支持 env 参数，可为会话持久化环境变量（如 venv 的 PATH/VIRTUAL_ENV），默认关闭。" },
      { category: "fix", text: "网络变化时连接页 IP 未刷新：后端改为独立 5s 轮询刷新地址，前端监听 online/focus 事件并在连接页提供手动刷新按钮。" },
      { category: "fix", text: "设置小红点每次进入软件都显示：首屏 status 未加载时不再误判为全部未读；进入设置页即标记已读。" },
      { category: "fix", text: "连接页 4 个卡片默认全展开：改为默认折叠、单选聚焦，老用户不再被引导霸屏。" },
    ],
  },
  {
    version: "2.3.13",
    date: "2026-07-22",
    items: [
      { category: "fix", text: "执行命令弹出黑框：发布版执行 cmd/bash 命令不再弹出黑色控制台窗口，命令在后台安静执行。" },
      { category: "fix", text: "关于卡片无故展开：没有新版本更新时，关于页「更新历史」卡片不再自动展开红点提示。" },
      { category: "improve", text: "后台命令整行可点：运行中或已结束的后台命令列表，点击整行即可展开查看输出，不必再精准点「查看输出」按钮。" },
      { category: "improve", text: "write_files 覆盖已有文件时自动保留原编码：原文件是 GBK 等中文编码时，会探测并沿用原编码，不再默认按 UTF-8 覆写导致中文乱码；新建文件或关闭自动识别时仍按 UTF-8。" },
    ],
  },
  {
    version: "2.3.12",
    date: "2026-07-22",
    items: [
      { category: "fix", text: "CI 构建失败：修复 `tauri build` 在 GitHub Actions 中找不到 tauri 命令的问题（预构建脚本改写 package.json 导致 PATH 丢失，改为分离执行 + npx 调用）。" },
    ],
  },
  {
    version: "2.3.11",
    date: "2026-07-21",
    items: [
      { category: "fix", text: "设置页每次打开都亮小红点：未读基准改为「上次浏览版本」或「当前运行版本」兜底，仅真有更新时才亮。" },
      { category: "fix", text: "托盘图标闪烁。" },
      { category: "fix", text: "IP 变化提示：连接页新增 IP 变化 banner 与倒计时提示。" },
      { category: "feat", text: "红点可点击引导：点设置 tab 红点或关于卡片红点，自动展开「更新历史」并滚动定位，看完数秒后自动标记为已读。" },
      { category: "feat", text: "连接页「接入模式」折叠区：原常驻的作用域选择收为手风琴第 1 折叠区，折叠头实时显示当前选中的模式；首次接入（无引导标记）默认四块全展开引导。" },
      { category: "improve", text: "更新检查弹框分流：自动 / 启动检查更新只在版本号上提示，仅手动点「检查更新」才弹「已是最新版本」框。" },
      { category: "improve", text: "首次接入引导更顺：首次全展开时页面不再自动滚动跳动（连接页与令牌管理的滚动逻辑跳过首屏）。" },
    ],
  },
];
